### ISSUE TITLE
抽卡分析卡进度

### ISSUE THREAD

**Issue by LaoshuBaby** [JamXi233/ZenlessTools#1]
![图片](https://github.com/JamXi233/ZenlessTools/assets/42690037/9946c1d2-9d83-4669-a672-8b3c98c026ae)
如图情况，游戏正常进行，时区很奇怪，游戏内依然可以正常继续往前往后滚页码

![图片](https://github.com/JamXi233/ZenlessTools/assets/42690037/8442126b-19da-4f14-832d-9440e13978d3)

在获取完所有独家频段以后，正常获取了音擎频段，然后常驻频段（之后就说限定池武器池常驻池了，不啰嗦）出问题了

我手动获取了恒等式本格后面那次失败的（最下面那个，只有链接没有结果）的json
如下

```json
{"retcode":0,"message":"OK","data":{"page":"1","size":"5","list":[{"uid":"24105587","gacha_id":"0","gacha_type":"1","item_id":"12004","count":"1","time":"2024-07-07 10:42:20","name":"「残响」-Ⅰ型","lang":"zh-cn","item_type":"音擎","rank_type":"2","id":"1720317600011879187"},{"uid":"24105587","gacha_id":"0","gacha_type":"1","item_id":"12002","count":"1","time":"2024-07-07 10:42:12","name":"「月相」-晦","lang":"zh-cn","item_type":"音擎","rank_type":"2","id":"1720317600011848487"},{"uid":"24105587","gacha_id":"0","gacha_type":"1","item_id":"12014","count":"1","time":"2024-07-07 10:42:05","name":"「恒等式」-变格","lang":"zh-cn","item_type":"音擎","rank_type":"2","id":"1720317600011818787"},{"uid":"24105587","gacha_id":"0","gacha_type":"1","item_id":"1101","count":"1","time":"2024-07-07 10:40:40","name":"珂蕾妲","lang":"zh-cn","item_type":"代理人","rank_type":"4","id":"1720317600011390587"},{"uid":"24105587","gacha_id":"0","gacha_type":"1","item_id":"12014","count":"1","time":"2024-07-07 10:40:40","name":"「恒等式」-变格","lang":"zh-cn","item_type":"音擎","rank_type":"2","id":"1720317600011390487"}],"region":"prod_gf_cn","region_time_zone":0}}
```

烦请作者看一下，是不是因为普池突然出来了一个角色“珂蕾妲”把分析器炸掉了

**Comment by LaoshuBaby** [comment]
后续，我出现问题的时候是在限定池的时候点击了详情，而我第二次重启软件后，在游戏内的常驻池里点击详情的时候（这样抓包抓到的第一个链接应该是常驻池的URL），就正常统计和分析了
![图片](https://github.com/JamXi233/ZenlessTools/assets/42690037/7e9982a3-9a96-4daf-9898-1899b473c692)

---

Edit: 感谢作者提醒，得知可能和 https://github.com/JamXi233/SRTools/issues/37 有类似之处

**Comment by JamXi233** [comment]
[ZenlessTools_1.0.2.0](https://github.com/JamXi233/ZenlessTools/releases/tag/1.0.2.0)已更新
已优化抽卡记录获取来避免该类问题
