### ISSUE TITLE
请求新增功能——添加国际服

### ISSUE THREAD

**Issue by JosteinPan** [JamXi233/ZenlessTools#11]
添加国际服，以便一启动器多端多账户（主要是我自己不会改国际服-bushi）链接包体在这（好像是替换文件实现的，但我好像失误不行）：https://github.com/ghhccghk/zenless_swich/releases

**Comment by JamXi233** [comment]
暂不计划添加。
该功能属于需长期维护的功能，每一版本都要使用不同的文件进行替换。
