### ISSUE TITLE
C盘安装权限问题

### ISSUE THREAD

**Issue by NOWorEVER** [JamXi233/ZenlessTools#2]
我安装在C盘，虽然不影响正常打开游戏，但是一直提示权限拒绝，有没有可以提权的方法，让客户端一直以管理员权限启动
![image](https://github.com/JamXi233/ZenlessTools/assets/57054154/fd124cc4-793f-453c-a426-d03db939aa2d)

**Comment by NOWorEVER** [comment]
类似创建快捷方式的方法，让启动的时候自带管理员权限，和胡桃一样

**Comment by JamXi233** [comment]
[ZenlessTools_1.0.4.0](https://github.com/JamXi233/ZenlessTools/releases/tag/1.0.4.0)已更新
**已新增管理员运行选项**
