### ISSUE TITLE
没做邦布频段的吗？

### ISSUE THREAD

**Issue by LaoshuBaby** [JamXi233/ZenlessTools#3]
![图片](https://github.com/JamXi233/ZenlessTools/assets/42690037/b38c44b8-e623-4b18-94b0-d7f1457e7e71)
不过这个并不是一开始就解锁的

**Comment by JamXi233** [comment]
[ZenlessTools_1.0.3.0](https://github.com/JamXi233/ZenlessTools/releases/tag/1.0.3.0)已更新
**已添加邦布频段**
