### ISSUE TITLE
UI布局需求

### ISSUE THREAD

**Issue by NOWorEVER** [JamXi233/ZenlessTools#4]
![image](https://github.com/user-attachments/assets/6595326d-d99a-4065-9d76-0bd2aecdd65c)
这边能做一个动态布局吗？不然这边看数据需要滚动查看
想截图有点麻烦

**Comment by JamXi233** [comment]
抽卡分析布局目前不会进行修改
已经通过增加[**创建截图**]功能解决该问题
**目前新版本尚未发布**

**Comment by JamXi233** [comment]
[ZenlessTools_1.0.5.0](https://github.com/JamXi233/ZenlessTools/releases/tag/1.0.5.0)版本已发布
✅添加抽卡分析创建截图功能
