### ISSUE TITLE
一些UI小问题

### ISSUE THREAD

**Issue by Lycoris02** [JamXi233/ZenlessTools#5]
1. 浅色模式下5星抽卡记录也是白色字体的，会看不清。
![QQ截图20240714155019](https://github.com/user-attachments/assets/87305e43-aceb-46f2-b28a-a9d03e2b355b)

2. 开始菜单里面还叫作星轨工具箱。
![QQ截图20240714155104](https://github.com/user-attachments/assets/ed6290a5-b92d-4ec4-b9a8-d43e858831d5)

**Comment by JamXi233** [comment]
感谢反馈，正在处理问题。

**Comment by JamXi233** [comment]
[ZenlessTools_1.0.5.0](https://github.com/JamXi233/ZenlessTools/releases/tag/1.0.5.0)版本已发布
✴️修复抽卡分析中S级超过80抽无法显示进度条的问题

**对于开始菜单名称显示错误我暂时没有复现，并不能确定是否已经修复**

**Comment by NOWorEVER** [comment]
一样的，截图功能文本颜色混乱
![image](https://github.com/user-attachments/assets/9feac7c7-821e-4817-8353-ff0cee7636c8)

**Comment by JamXi233** [comment]
@NOWorEVER 
**截图背景不跟随程序设置**目前为已知问题，会在下一版本修复。
目前缓解方法：使用跟随系统主题

**Comment by JamXi233** [comment]
@NOWorEVER #6
