### ISSUE TITLE
系统设置缩放布局，截图导出内容异常

### ISSUE THREAD

**Issue by NOWorEVER** [JamXi233/ZenlessTools#7]
![image](https://github.com/user-attachments/assets/da43f8b1-937a-42db-8bdb-e3b3c055f427)

**Comment by JamXi233** [comment]
[ZenlessTools_1.0.6.0](https://github.com/JamXi233/ZenlessTools/releases/tag/1.0.6.0)已发布
✴️修复使用缩放后抽卡截图功能显示不完整的问题
